name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the image (e.g., v2.5.0)'
        required: false
        default: 'manual'
        type: string

permissions: {}

env:
  GOLANG_VERSION: '1.23' # Note: go-version must also be set in job controller-image.with.go-version & plugin-image.with.go-version.

jobs:
  controller-image:
    permissions:
      contents: read
      packages: write # Required and used to push images to `ghcr.io` if used.
      id-token: write # For creating OIDC tokens for signing.
    uses: ./.github/workflows/image-reuse.yaml
    with:
      quay_image_name: quay.io/yohanko1/argo-rollouts:${{ github.event_name == 'workflow_dispatch' && inputs.tag_name || github.ref_name }}
      # Note: cannot use env variables to set go-version (https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations)
      go-version: '1.23'
      platforms: linux/amd64,linux/arm64
      push: true
    secrets:
      quay_username: ${{ secrets.QUAY_USERNAME }}
      quay_password: ${{ secrets.QUAY_ROBOT_TOKEN }}
